services:
  php-fpm:
    image: ghcr.io/erikngigi/magento-php8.3-fpm:latest
    hostname: magento-php-fpm
    container_name: magento-php-fpm
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: magento
      SERVICE_TAGS: development
    volumes:
      - ./src/magento:/var/www/html:cached
      - ./templates/php-config/php.ini-development:/usr/local/etc/php/php.ini:ro
    expose:
      - "9000:9000"
    networks:
      - magento-app-network
  nginx:
    image: ghcr.io/erikngigi/magento-nginx-1.29:latest
    hostname: magento-nginx
    container_name: magento-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - ./src/magento:/var/www/html:cached
      - ./src/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./src/nginx/conf.d:/etc/nginx/conf.d:ro
    networks:
      - magento-app-network
    depends_on:
      - php-fpm
networks:
  magento-app-network:
    name: magento-app-network
    driver: bridge
