name: Build and push PHP-FPM Docker image for Magento 2.4.7 to Github Container Registry.
on:
  push:
    branches: ["main"]
    paths:
      - 'docker/php-fpm/**'
      - '.github/workflows/build-php-fpm-magento.yml'
  workflow_dispatch:
    inputs:
      tags:
        description: 'Custom tag for the image (optional)'
        required: false
        default: 'latest'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./docker/php-fpm
          file: ./docker/php-fpm/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ vars.GHCR_USERNAME }}/magento-php8.3-fpm:latest
            ${{ vars.DOCKERHUB_USERNAME }}/magento-php8.3-fpm:latest
      - name: Image build complete
        run: echo "✅ PHP-FPM Magento Docker image built and pushed successfully."
